### ISSUE TITLE
Training the model on custom dataset

### ISSUE THREAD

**Issue by huaweiping** [chenhaoxing/DiffusionInst#18]
Hi, I have a custom 512x512 dataset with 2 channels (set the third one to zero) and I want to train the model with that dataset. The dataset is a coco-like dataset and validated by detectron2. Everything looks fine except the training result. This is the result after 45000 iterations.:

```
[07/04 10:44:50 d2.engine.defaults]: Evaluation results for my_dataset_val in csv format:
[07/04 10:44:50 d2.evaluation.testing]: copypaste: Task: bbox
[07/04 10:44:50 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[07/04 10:44:50 d2.evaluation.testing]: copypaste: 10.3947,25.5441,8.5027,10.7150,8.7438,nan
[07/04 10:44:50 d2.evaluation.testing]: copypaste: Task: segm
[07/04 10:44:50 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[07/04 10:44:50 d2.evaluation.testing]: copypaste: 3.2318,7.6850,1.9359,2.9650,7.0297,nan
```

The dataset only contain 2 classes so I modify the num_classes in the diffinst.coco.res50.yaml file and use diffinst.coco.res50.inst.yaml as the Instance Segmentation configuration file.  This is the diffinst.coco.res50.yaml file:

```
_BASE_: "Base-DiffusionInst.yaml"
MODEL:
  WEIGHTS: 
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionInst:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST:  ("my_dataset_val",)
SOLVER:
  STEPS: (350000, 420000) #(87500, 105000) #(350000, 420000)
  MAX_ITER: 450000 #112500 #450000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
```

The image crop size is modified to 512x512 in the base config file. I also abadon the pre-trained weights as this dataset is far from generall objects in either ImageNet or Coco dataset. Nothing else is significantly changed in the code or configuration file.

I believe I did something wrong but have no idea of that. Can anyone help me figure it out?
